# General configuration

version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

# Environment configuration

image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

clone_depth: 1

# Build configuration

before_build:
  - dotnet --version
  - dotnet restore --verbosity m
  - nuget restore

build_script:
  - dotnet publish

after_build:
  - choco install opencover.portable
  - choco install codecov

# Tests configuration

test_script:
  - OpenCover.Console.exe
    -target:"C:\Program Files\dotnet\dotnet.exe"
    -targetargs:"test"
    -output:coverage.xml
    -oldStyle
    -filter:"+[Pecuniary.Transaction.Query*]* -[Pecuniary.Transaction.Tests*]*"
    -register:user
  - codecov -f "coverage.xml"

# Artifacts configuration

artifacts:
  - path: \Pecuniary.Transaction.Query\bin\Debug\netcoreapp2.1\publish
    name: artifact
    type: zip

# Deployment configuration

deploy: off