AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pecuniary Transaction query microservice

Parameters:
  AppName:
    Description: Application name
    Type: String
    Default: Pecuniary
  PecuniaryAuthStackParameter:
    Type: String
    Default: pecuniary-auth-stack
  PecuniaryDbStackParameter:
    Type: String
    Default: pecuniary-db-stack
  PecuniaryTopicsStackParameter:
    Type: String
    Default: pecuniary-topics-stack

Mappings:
  Constants:
    Application: 
      Name: Pecuniary

Globals:
  Function:
    Timeout: 30

Resources:
  PecuniaryWebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: 
                Fn::Sub:
                    - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
                    - UserPoolId:
                        Fn::ImportValue:
                          !Sub ${PecuniaryAuthStackParameter}-PecuniaryCognitoUserPoolId
            Identity:
              Header: Authorization
      Tags:
        AppName: !FindInMap [Constants, Application, Name]

  TransactionEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-TransactionEvent
      Handler: Pecuniary.Transaction.Events::Pecuniary.Transaction.Events.Function::TransactionEventHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: Pecuniary.Transaction.Events/bin/Release/netcoreapp2.1/publish
      MemorySize: 384
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryDbStackParameter}-PecuniaryESReadStoreDomain
      Events:
        TransactionCreatedEventTopic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniaryTransactionCreatedEventTopicArn
      Policies: 
        - AmazonSNSReadOnlyAccess
      Tags:
        AppName: !Ref AppName 

  TransactionQueryWebApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-TransactionQuery
      Handler: Pecuniary.Transaction.Query::Pecuniary.Transaction.Query.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: Pecuniary.Transaction.Query/bin/Release/netcoreapp2.1/publish
      MemorySize: 384
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryDbStackParameter}-PecuniaryESReadStoreDomain
      Events:
        GetValues:
          Type: Api
          Properties:
            RestApiId: !Ref PecuniaryWebApi
            Path: /api/transaction/{id}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
      Tags:
         AppName: !Ref AppName

Outputs:
  PecuniaryApiGatewayBaseUrl:
    Description: Base Url of the Pecuniary Transaction Query API Gateway
    Value: !Ref PecuniaryWebApi
    Export:
      Name: !Sub ${AWS::StackName}-PecuniaryApiGatewayBaseUrl